# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791e93f816496c7f5079488f08c151a12ead69bf40245ef0de2538d2a7327d07bbc896059bc6687fd39a13293ac29471701256441ad2cb3cea04062847700a47

test:
  secret_key_base: 9599b1645dc3d084cc50ce0e466c10ef7da390d386ef81fd341ceba8292356bf3f654d700bed598eef5834ff5f42bf326ba80e38e217d1e98c112bdf3898cf88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
