# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4497ea331722cfe3bb6120abc418c82bddefb93d21373fd543ca2b98f75c54cffa45a19e8457f5f4c441722c8654e96439754dfc6c897126dfd1689ac72bf3a5

test:
  secret_key_base: 2a3bf747e41c207a6aca47001877cd2152625014dc1abfe52feda12c5f940680fbd8432e7a49f18f11f56abb911c7825818dcb0e878bced49f830286301271c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
