# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f54cf33231007bb79bb124c0e04e18d2b9b22b2e4c0701ec07520d18ea6fe933332e72a964633515907b7ed9052e6d403123526f219551778cf3d8d202f14adb

test:
  secret_key_base: 6474d100b153cdc7def03718dfde7a066e31cbd26513afb581274e04d694434a8e9d2e92741d8589843d3b0920663492d16bed6cbda6ebc37d149fca3695e4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
